package com.apes.main.enums;

public enum PanelType {
	MAIN_PANEL, NEW_GAME_PANEL, LOAD_GAME_PANEL, RESUME_GAME_PANEL, 
	OPTIONS_PANEL, ENEMY_CREATOR_PANEL, QUESTION_CREATOR_PANEL, CONFIG_PANEL, 
	ABOUT_PANEL, HELP_PANEL
}
